### ISSUE TITLE
Login page not shown, I go directly to the index.html page

### ISSUE THREAD

**Issue by mpaletti** [xreef/WebServer-Esp8266-ESP32-Tutorial#1]
Hi, i have a big problem with this project: When i type the ip addess of the esp8266 (I have the esp-01 version and it gives no error when I load the sketch or the folder with the html files) I am shown the index page and not the login page which I can only see if I type /login.html manually on the address bar. 
I copied and pasted the code you posted [here](https://www.mischianti.org/2020/11/09/web-server-with-esp8266-and-esp32-manage-security-and-authentication-4/?unapproved=14386&moderation-hash=0bda70081f6fec74baa8e98388eaf168#comment-14386) without making any changes but it doesn’t work … Even changing browser and deleting cache and cookies the login page is not shown. 

In the serial console this is shown: 
`Connected to FRITZ!Box 7590 
IP address: 192.168.2.50 
Inizializing FS…done. 
Set routing for http server! 
Go on not found! 
Set cache! 
HTTP server started 
On not found handleFileRead: /favicon.ico 
Enter is_authenticated 
Authentication Failed 
Go on not login! 
     Sent file: /login.html of size 4711 
On not found handleFileRead: /favicon.ico 
Enter is_authenticated 
Authentication Failed 
Go on not login! 
     Sent file: /login.html of size 4711`

**Comment by xreef** [comment]
Check the answer on article comment.
Bye RM
